own.port: 8000

# Var names are chosen such that services addresses would be injected by kube
word.service.host: word.gen
word.service.port: 10000
number.service.host: number.gen
number.service.port: 10000
internets.service.host: internets.gen
internets.service.port: 10000
