own.port: 8000

# Var names are chosen such that services addresses would be injected by kube
gen.word.service.host: ~
gen.word.service.port: ~
gen.number.service.host: ~
gen.number.service.port: ~
gen.internets.service.host: ~
gen.internets.service.port: ~
