apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gen
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gen
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gcr.io/word-gen-314/gateway
        ports:
        - containerPort: 8000
          name: http
