presubmits:
  yb172/experiments:
  - name: test-job
    decorate: false
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command:
        - "/bin/printenv"
    trigger: "(?m)^/test this"
    rerun_command: "/test this"    

sinker:
  resync_period: 1m
  max_prowjob_age: 2h
  max_pod_age: 30m
