plugins:
  yb172/experiments:
  - size
  - config-updater
  - trigger

config-updater:
  maps:
    # Update the config configmap whenever config.yaml changes
    kube/config.yaml:
      name: config
    # Update the plugins configmap whenever plugins.yaml changes
    kube/plugins.yaml:
      name: plugins

triggers:
  - repos:
    - yb172/experiments
