own.port: 10000

# Var names are chosen such that services addresses would be injected by kube
gen.word.service.host: ~
gen.word.service.port: ~
gen.internets.service.host: ~
gen.internets.service.port: ~
