apiVersion: v1
kind: Service
metadata:
  name: gen-number
  namespace: gen
  labels:
    app: gen-number
spec:
  ports:
    - port: 10000
      name: gen-number
  selector:
    app: gen-number
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-number
  namespace: gen
  labels:
    app: gen-number
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gen-number
  template:
    metadata:
      labels:
        app: gen-number
    spec:
      containers:
      - name: gen-number
        image: gcr.io/word-gen-314/gen-number
        ports:
        - containerPort: 10000
