apiVersion: v1
kind: Service
metadata:
  name: number
  namespace: gen
  labels:
    app: number
spec:
  clusterIP: None
  ports:
    - port: 10000
      name: grpc
  selector:
    app: number
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number
  namespace: gen
  labels:
    app: number
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number
  template:
    metadata:
      labels:
        app: number
    spec:
      containers:
      - name: number
        image: gcr.io/word-gen-314/number
        ports:
        - containerPort: 10000
          name: grpc
