apiVersion: v1
kind: Service
metadata:
  name: internets
  namespace: gen
  labels:
    app: internets
spec:
  clusterIP: None
  ports:
    - port: 10000
      name: grpc
  selector:
    app: internets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internets
  namespace: gen
  labels:
    app: internets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internets
  template:
    metadata:
      labels:
        app: internets
    spec:
      containers:
      - name: internets
        image: gcr.io/word-gen-314/internets
        ports:
        - containerPort: 10000
          name: grpc
