apiVersion: v1
kind: Service
metadata:
  name: gen-word
  labels:
    app: gen-word
spec:
  ports:
    - port: 10000
      name: gen-word
  selector:
    app: gen-word
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-word
  labels:
    app: gen-word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gen-word
  template:
    metadata:
      labels:
        app: gen-word
    spec:
      containers:
      - name: gen-word
        image: gcr.io/word-gen-314/gen-word
        ports:
        - containerPort: 10000
