apiVersion: v1
kind: Service
metadata:
  name: word
  namespace: gen
  labels:
    app: word
spec:
  clusterIP: None
  ports:
    - port: 10000
      name: grpc
  selector:
    app: word
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word
  namespace: gen
  labels:
    app: word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word
  template:
    metadata:
      labels:
        app: word
    spec:
      containers:
      - name: word
        image: gcr.io/word-gen-314/word
        ports:
        - containerPort: 10000
          name: grpc
