# This is a basic workflow that is manually triggered

name: On release workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "print_message"
  print_message:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: echo "Hello. Today is $(date +%Y-%m-%d), and it looks like release $(echo ${GITHUB_REF} | cut -c 11-) was created"
